name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish NuGet Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Check for changes in project files
        id: check-changes
        run: |
          git fetch origin main

          # Получаем изменённые файлы
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "CHANGED_FILES: $CHANGED_FILES"

          # Фильтруем файлы, относящиеся к проекту
          ESSENTIAL_CHANGES=$(echo "$CHANGED_FILES" | grep -E "src/WC.Library.BCryptPasswordHash|src/WC.Library.BCryptPasswordHash.Abstactions")
          echo "Filtered essential changes: $ESSENTIAL_CHANGES"

          if [ -z "$ESSENTIAL_CHANGES" ]; then
            echo "No essential changes detected. Skipping publish."
            echo "should_publish=false" >> $GITHUB_ENV
            exit 0
          else
            echo "Changes detected in project files."
            echo "should_publish=true" >> $GITHUB_ENV
          fi

      - name: Check if we need to continue
        if: env.should_publish == 'false'
        run: |
          echo "No changes detected, skipping version increment and publishing."
          exit 0

      - name: Get latest version for WC.Library.BCryptPasswordHash
        if: env.should_publish == 'true'
        id: get-version-bcrypt
        run: |
          PACKAGE_ID="wc.library.bcryptpasswordhash"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "New version for $PACKAGE_ID: $NEW_VERSION"
          echo "bcrypt_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Get latest version for WC.Library.BCryptPasswordHash.Abstactions
        if: env.should_publish == 'true'
        id: get-version-abstractions
        run: |
          PACKAGE_ID="wc.library.bcryptpasswordhash.abstactions"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "New version for $PACKAGE_ID: $NEW_VERSION"
          echo "abstractions_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update version in WC.Library.BCryptPasswordHash
        if: env.should_publish == 'true'
        run: |
          dotnet build src/WC.Library.BCryptPasswordHash/WC.Library.BCryptPasswordHash.csproj /p:Version=${{ env.bcrypt_version }}

      - name: Update version in WC.Library.BCryptPasswordHash.Abstactions
        if: env.should_publish == 'true'
        run: |
          dotnet build src/WC.Library.BCryptPasswordHash.Abstactions/WC.Library.BCryptPasswordHash.Abstactions.csproj /p:Version=${{ env.abstractions_version }}

      - name: Build and pack WC.Library.BCryptPasswordHash
        if: env.should_publish == 'true'
        run: |
          dotnet pack src/WC.Library.BCryptPasswordHash/WC.Library.BCryptPasswordHash.csproj -c Release -o ./out

      - name: Build and pack WC.Library.BCryptPasswordHash.Abstactions
        if: env.should_publish == 'true'
        run: |
          dotnet pack src/WC.Library.BCryptPasswordHash.Abstactions/WC.Library.BCryptPasswordHash.Abstactions.csproj -c Release -o ./out

      - name: Publish packages to NuGet
        if: env.should_publish == 'true'
        run: |
          dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
